### ISSUE TITLE
[BadMethodCallException]   Call to undefined method [package]

### ISSUE THREAD

**Issue by inhedron** [potsky/laravel-localization-helpers#17]
Hi,
when i try to run php artisan localization:missing i got an error like that:   
[BadMethodCallException]  Call to undefined method [package]

it looks like the package() method was deleted from src/Illuminate/Config/Repository.php in this commit:

https://github.com/laravel/framework/commit/64c15a35d9578748671639748b83b21d16dbd6c2

Can you fix ?

**Comment by potsky** [comment]
Hi !

Since which version the `package` method has been removed ? Since version `5.2.5` ?

Do I just have to remove this method from the service provider boot method to make it work for Laravel >= v5.2.5 ?

Are you sure you are using v1.3.2 and not the dev-master version ?

I cannot test L5 before next week... so I can only make a blind fix for the moment if you tell me what to do :-)

**Comment by potsky** [comment]
Ok found...

The documentation is not up to date !

There is a special service provider to load for Laravel 5.

Please read the documentation of the last *Tag* available here : <https://github.com/potsky/laravel-localization-helpers/blob/v1.3.2/README.md>
