### ISSUE TITLE
Automatic translations

### ISSUE THREAD

**Issue by marvinschroeder** [potsky/laravel-localization-helpers#23]
How is the automatic translations option working?

Looking in the code, we guess it's taking the last part of the "lemma" and translates it to a specific language, taking the `default_language` from the config.

Is it possible to define the `default_language` where everything is already translated and translate the values of the "lemmas" to the values of the "lemmas" of the other languages? So we could give all the right translations in our own native language and translate it to the languages we would like to use in our project.

**Comment by potsky** [comment]
You just need to create a Microsoft account as explained at the end of the configuration file <https://github.com/potsky/laravel-localization-helpers/blob/master/src/config/config.php>

The `default_language` is the language that you use when writing lemma in your PHP code in `trans` functions etc... It is optional since the Microsoft API automatically guess your input language. Set it only if translation is totally buggy.

To make the translation work, you must of course use this kind of lemma : `trans('message.You can use this work')` and not `trans('message.message1')`.

The translation is done in the target language according to the name of the folder in the `lang` folder. For example, LLH will translate in french all new lemma in file `lang/fr/message.php` and in german all new lemma in file `lang/de/message.php`, ...

If you want to translate already translated lemma, you just have to remove from lang files these lemma and run the command again.
