### ISSUE TITLE
Need help. What is "family"?

### ISSUE THREAD

**Issue by andreich1980** [potsky/laravel-localization-helpers#48]
I ran `localization:missing` and got messages like that
```
New account in file \resources\views\accounts\create.blade.php will not be included because it has no family
```
What is the family?

Strings in my blades are like:
```
@lang('New account')
```

Strings in my controllers are like:
```
echo trans(
    'Created :createdCount. Updated :updatedCount',
    compact('createdCount', 'updatedCount')
);
```

Please help me.

**Comment by potsky** [comment]
Hello,

the family is the name of the lang file. e.g. : `@lang('message.New account')`
Laravel will search in the `lang/xx/message.php` file for array key `New account` and get the corresponding value.

If you simply write `@lang('New account')`, I don't know where Laravel can search. Perhaps it is a new feature (because I don't have write a line of Laravel code for several months) but I don't think so...
