### ISSUE TITLE
support for Laravel 5.5?

### ISSUE THREAD

**Issue by vesper8** [potsky/laravel-localization-helpers#64]
I think all you need to do is change the illuminate/support from 5.4.* to 5.5.*

**Comment by limenet** [comment]
I've been using a [fork](https://github.com/limenet/laravel-localization-helpers) for a few weeks now where I added support for Laravel 5.5 and it seems to be working fine. You can use it by adding

```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/limenet/laravel-localization-helpers"
    }
],
```

to your `composer.json` or wait until #65 is merged.

**Comment by potsky** [comment]
Hi !

I will take a look on the PR and adapt tests to remove PHP5.6 given that PHP7+ is required for Laravel 5.5 and given I have no more time to upgrade the microsoft translation package.

**Comment by limenet** [comment]
@potsky if you want me to, I can work on adapting the tests and include it with the PR!

**Comment by potsky** [comment]
@limenet Thank you very much for this proposition ! I am very happy to have a contributor ;-)

I have merged your PR and change some (dirty) thing from my code.

The test problem is due to the Microsoft API change. My package depends on an other package of mine : https://github.com/potsky/microsoft-translator-php-sdk

It must be updated to support the new Microsoft endpoints.

If you can do this, it is awesome. If not, I will remove the auto-translation feature from this package and it will be ok !

**Comment by limenet** [comment]
@potsky You're welcome!

I just came across the same issue you mentioned about the Microsoft API change. Since I have no experience at all with Microsoft's Translation API (and also don't use it in combination with this package), I'm afraid, all I can help you with, is fixing the other tests and getting them ready for PHP 7.

I've already updated some packages etc. so the test suite is compatible with PHP 7 but there are a few tests that are failing (apart from the Microsoft Translation API). I'll work on these and then open a PR -- unfortunately, without being able to work on the auto-translation, sorry!

**Comment by potsky** [comment]
@limenet don't bother with this, I am on the track with this now ;-)

Publish in a few moment

**Comment by potsky** [comment]
PHP CS Fixer has changed rrrggg. Need to change the doc, the code, etc...

**Comment by potsky** [comment]
Ok done. Master branch is ok. I will publish a new branch for Laravel 5.5
